title: The Unified Gospel Library
description: An expanded harmony of the Gospels with prophetic and historical insight.
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
url: "https://dizzy-marville.github.io"
baseurl: "/unified-gospel-narrative"
permalink: /:categories/:year/:month/:day/:title:output_ext
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title:output_ext

markdown: kramdown
